parse_config:
  raw_binding_map:
    "&kp JP_SEMI": "JP SEMI"
    "&kp JP_COMMA": "JP COMMA"
    "&kp JP_DOT": "JP DOT"
    "&kp JP_FSLH": "JP FSLH"
    "&kp JP_N0": "JP N0"
    "&kp JP_N1": "JP N1"
    "&kp JP_N2": "JP N2"
    "&kp JP_N3": "JP N3"
    "&kp JP_N4": "JP N4"
    "&kp JP_N5": "JP N5"
    "&kp JP_N6": "JP N6"
    "&kp JP_N7": "JP N7"
    "&kp JP_N8": "JP N8"
    "&kp JP_N9": "JP N9"
    "&kp JP_MINUS": "JP MINUS"
    "&kp JP_CARET": "JP CARET"
    "&kp JP_BACKSLASH": "JP BSLH"
    "&kp JP_LBKT": "JP LBKT"
    "&kp JP_RBKT": "JP RBKT"
    "&kp JP_AT": "JP AT"
    "&kp JP_COLON": "JP COLON"
    "&kp JP_STAR": "JP STAR"
